spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: schema.sql
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
